name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm install

      - name: Setup Git
        run: |
          git config user.name 'tatemz'
          git config user.email 'tatemz@proton.me'

      - name: bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
